### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by NuriddinK** [peerigon/parse-domain#101]
Sites containing multiple subdomains not correctly parsed.

example: **www.vic.gov.au** 

response: **{ tld: 'vic.gov.au', domain: 'www', subdomain: '' }**

**Comment by jhnns** [comment]
What was the desired behavior? The response looks correct to me since vic.gov.au is listed as top-level domain in the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat)
