### ISSUE TITLE
Property 'subDomains' does not exist on type 'ParseResult'

### ISSUE THREAD

**Issue by edward-s** [peerigon/parse-domain#106]
After upgrading to latest 3.0.1, running the sample code in my typescript codebase produces a typescript warning that Property 'subDomains' does not exist on type 'ParseResult'
```

// ts-warnings!!
const { subDomains, domain, topLevelDomains } = parseDomain(
    // This should be a string with basic latin characters only.
    // More information below.
    'www.some.example.co.uk',
  );

  console.log(subDomains); // ["www", "some"]
  console.log(domain); // "example"
  console.log(topLevelDomains);
```

**Comment by jhnns** [comment]
That's correct. There are different parse results now. You need to check for the `type` (see [Expected output](https://github.com/peerigon/parse-domain#expected-output)). We recommend using a [`switch` statement](https://github.com/peerigon/parse-domain#-switch-over-parseresulttype-to-distinguish-between-different-parse-results).

**Comment by edward-s** [comment]
the first example is misleading then. please update it to so that other developers do not make the same mistake

**Comment by jhnns** [comment]
I wanted to show a contrived example that shows how it basically works, but yeah, it's misleading. I've updated it. Thanks for the feedback.
