### ISSUE TITLE
parseDomain 3.0.1 don't parse a simple domain in a production build made with CRA

### ISSUE THREAD

**Issue by PlanetIrata** [peerigon/parse-domain#109]
Hi, I'm using parse-domain in a React App built with `create-react-app`, it work without any issue in local builds, but failed to parse a simple domain like `toto.com` in production build, always reporting that the first character is invalid :

```
{
   "type": "INVALID",
   "hostname": "toto.com",
   "errors": [
      {
         "type": "LABEL_INVALID_CHARACTER",
         "message": "Label \"toto\" contains invalid character \"t\" at column 1.",
         "column": 1
      },
      {
         "type": "LABEL_INVALID_CHARACTER",
         "message": "Label \"com\" contains invalid character \"c\" at column 1.",
         "column": 1
      }
   ]
}
(18.af1f7fcc.chunk.js, line 1)
```

Since production build are minified, this issue may be related to #107 ? (but no error is reported while building)

Thanks for help.

**Comment by jhnns** [comment]
parse-domain assumes an ES2015 environment. The [sanitize.ts module uses the `u` RegExp flag](https://github.com/peerigon/parse-domain/blob/master/src/sanitize.ts#L152) which [has been added with ES2015](https://mathiasbynens.be/notes/es6-unicode-regex). Maybe it's related to this?

If you're using webpack, I recommend a loader configuration like this:

```js
// webpack.config.js

const {resolve} = require('path');

module.exports = {
    module: {
        rules: [
            {
                include: [
                    resolve(__dirname, 'node_modules', 'parse-domain'),
                ],
                test: /\.js$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            cacheDirectory: true,
                            sourceType: 'unambiguous',
                            presets: [
                                [
                                    '@babel/preset-env',
                                    {
                                        useBuiltIns: 'usage',
                                        corejs: 3,
                                        targets: {
                                            // See https://babeljs.io/docs/en/babel-preset-env#options
                                        }
                                    },
                                ],
                            ],
                        },
                    },
                ],
            },
        ],
    },
};
```

If this doesn't fix your issue, can you come up with a reproducible test case?

**Comment by PlanetIrata** [comment]
Sorry, I needed a fix, so I switched to [psl](https://github.com/lupomontero/psl).
 
But the issue seems related to #26 and/or #107 🤷🏻‍♂️ 

Great work anyway. Thanks.

**Comment by networkchimp** [comment]
This is a blocker for us too.  It becomes very inconvenient to require Babel to use this.
