### ISSUE TITLE
Missing types key on package.json file

### ISSUE THREAD

**Issue by Cervantes007** [peerigon/parse-domain#111]
Issue:
package.json file must have a key  "types" or "typings" with a value related to the library typescript definition files.

Why?
My IDE doesn't recognize parse-domain types, see picture below:
![Screenshot_20200505_115220](https://user-images.githubusercontent.com/15332426/81087337-96ed6d80-8ec7-11ea-9994-a108816e7d1c.png)

You can check this in the typescript official doc:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Solution add this entry to package.json
"types": "./build-esm/src/main.d.ts"

I already create a very simple merge-request  https://github.com/peerigon/parse-domain/pull/110
I hope it helps a little bit. 

By the way, great job in this package, thank you guys, it was very helpful.

Greetings.

**Comment by jhnns** [comment]
Thanks. I merged the PR :+1:
