### ISSUE TITLE
IPv6 URL's not parsed correctly, however IPv4 are

### ISSUE THREAD

**Issue by niftylettuce** [peerigon/parse-domain#114]
```sh
❯ node
Welcome to Node.js v12.18.0.
Type ".help" for more information.
> const { fromUrl, NO_HOSTNAME } = require('parse-domain');
undefined
> fromUrl('1.2.3.4/host')
'1.2.3.4'
> fromUrl('::af/host')
Symbol(NO_HOSTNAME)
> fromUrl('1234:1234:123:21::21/host')
Symbol(NO_HOSTNAME)
>
```

**Comment by jhnns** [comment]
IPv6 addresses need to be surrounded by `[]` in URLs, e.g. `http://[1:2:3:4:5:6:7:8]/path?query`
See https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2

I added experimental support for these invalid URLs in `v7.0.0` but might remove it again if there are any other problems.
