### ISSUE TITLE
*Important* Core bug with parsing

### ISSUE THREAD

**Issue by niftylettuce** [peerigon/parse-domain#115]
Example below shows `Symbol(NO_HOSTNAME)` returned instead of `www.just-eat.es` or `just-eat.es`:

```
> const { fromUrl } = require('parse-domain');
undefined
> fromUrl('www.just-eat.es')
Symbol(NO_HOSTNAME)
> fromUrl('www.justeat.es')
Symbol(NO_HOSTNAME)
> fromUrl('justeat.es')
Symbol(NO_HOSTNAME)
```

**Comment by niftylettuce** [comment]
I'm just going to use another library, this lib isn't really worthwhile, thank you though

**Comment by jhnns** [comment]
Looks like you're using an older Node version (< 10) where the global `URL` constructor is not available yet ([see also](https://nodejs.org/api/url.html#url_the_whatwg_url_api)). Please make sure to include a polyfill (as stated in the README):

```
➜ node
Welcome to Node.js v14.5.0.
Type ".help" for more information.
> const {fromUrl} = require("./build-cjs/src/main.js")
undefined
> fromUrl("www.just-eat.es")
'www.just-eat.es'
```

**Comment by jhnns** [comment]
I added a helpful error message
