### ISSUE TITLE
Why is 127.0.0.1 not marked as reserved?

### ISSUE THREAD

**Issue by joekaiser** [peerigon/parse-domain#117]
Evaluating `localhost` returns ` { type: 'RESERVED', hostname: 'localhost', labels: [ 'localhost' ] }`

but evaluating `127.0.0.1` returns `{ type: 'IP', hostname: '127.0.0.1', ipVersion: 4 }`

Although technically true, shouldn't [reserved IP address](https://en.wikipedia.org/wiki/Reserved_IP_addresses) be marked as such?

**Comment by joekaiser** [comment]
https://www.npmjs.com/package/ip-range-check

What I did is use the package above to determine if an IP is reserved. It is really simple when used in conjunction with parse-domain

**Comment by jhnns** [comment]
Thanks for asking 😀. Parsing and evaluating IPs is out of scope for parse-domain. I added a note to the README.

**Comment by joekaiser** [comment]
That makes sense. It is easy enough to take the list of reserved IPs from wikipedia and use the ip-range-check package to compare against it. I would argue it is better anyway and keeps this package smaller
