### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by famouspotatoes** [peerigon/parse-domain#120]
Hi! Thank you for the excellent package.

The only issue I found was that `parseDomain()` is typed to only return keys: `type`

The other keys such as `subDomains` and `domain` and `topLevelDomains` are not expected to be returned. As a result, I have to use @ts-ignore to prevent errors.

I know this package hasn't been worked on in some months, but just wanted to point it out.

**Comment by famouspotatoes** [comment]
![Uploading Screen Shot 2020-12-09 at 5.12.45 PM.png…]()

**Comment by famouspotatoes** [comment]
<img width="518" alt="Screen Shot 2020-12-09 at 5 13 17 PM" src="https://user-images.githubusercontent.com/48636156/101699959-d5d93800-3a41-11eb-86cb-6285e3951481.png">

**Comment by famouspotatoes** [comment]
To illustrate better what I'm trying to achieve, here are the two approaches.

This is the first one that is my ideal usage, but is not allowed due to typescript issues (throws error shown above in screenshot):
```
// Parse and destructure in a single step for the fields I want (undefined values are acceptable)
const {subDomains, domain, topLevelDomains, type}: ParseResult = parseDomain(fullDomain)
```

Workaround approach (more verbose)
```
// Parse domain 
const parseResult: ParseResult = parseDomain(fullDomain)

// Add check to make sure type is Listed
if (parseResult.type !== ParseResultType.Listed){
   // Now we can safely destructure since we know it is ParseResultType.Listed
   const {subDomains, domain, topLevelDomains, type} = parseResult
}
```

**Comment by jhnns** [comment]
The workaround you've mentioned is actually the way it's supposed to work. You need to check for `ParseResultType.Listed` first before accessing `subDomains`, `domain` and `topLevelDomains`. `subDomains`, `domain` and `topLevelDomains` make only sense if the domain was listed in the public suffix list. It's explained in the README 😉

**Comment by famouspotatoes** [comment]
Ok that makes sense now, thank you for clarifying!
