### ISSUE TITLE
Angular 10 Warning about CommonJS or AMD dependencies

### ISSUE THREAD

**Issue by ryaa** [peerigon/parse-domain#121]
Angular 10 now gives a warning to users who are using this library due to is-ip library used which is being a CommonJS package.

`Warning: /Users/alexryltsov/Git/BOSSDesk2/chore-BDM-119-fix-commonJS-or-AMD-dependencies-warnings/node_modules/parse-domain/build-esm/src/sanitize.js depends on 'is-ip'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

**Comment by jhnns** [comment]
Thanks for letting me know. I'll see if there's a newer version or maybe we switch to another package.

**Comment by jhnns** [comment]
parse-domain v7.0.0 is now an ECMAScript module (and all its dependencies).
