### ISSUE TITLE
Problem with IP dependency?

### ISSUE THREAD

**Issue by dleangen** [peerigon/parse-domain#127]
Hi!

Nice lib. I wanted to import it into an Angular App, and got this error:

```
  node_modules/is-ip/index.d.ts:64:1
    64 export = isIp;
       ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

I can of course set this flag, but I would prefer not. From my perspective as the user of the lib, the lib should not force me to have to change compiler options. 😀

Would it be possible to update this so users don't have to worry about it?

I did not have permission to create a PR, so I have attached a patch. I did not test, but I think that ought to do the trick.

Thanks!!

[patch.diff.txt](https://github.com/peerigon/parse-domain/files/6471110/patch.diff.txt)

**Comment by jhnns** [comment]
I've updated the dependencies. Do you still get an error?

**Comment by XPalpatineX** [comment]
Same error in node_modules/parse-domain/build-esm/src/sanitize.d.ts:1:8.  import isIp from "is-ip";
