### ISSUE TITLE
string ends with dot is recognized as valid domain

### ISSUE THREAD

**Issue by librz** [peerigon/parse-domain#129]
```javascript
const result = parseDomain("example.co.jp."); // string ends with a dot
if (result.type === ParseResultType.Listed) {
  console.log(":(")
}
```

**Comment by jhnns** [comment]
`"example.co.jp."` is a valid domain. The empty label in the end is the root label and considered to be valid.

See [Fully qualified domain name](https://en.wikipedia.org/wiki/Fully_qualified_domain_name)
