### ISSUE TITLE
result.domain not correct

### ISSUE THREAD

**Issue by librz** [peerigon/parse-domain#132]
```javascript
const result = parseDomain(`amazonaws.com`);
console.log(result);
```

result.type is listed, however, result.domain is undefined, which is very strange

**Comment by librz** [comment]
result.icann.domain has value though

**Comment by jhnns** [comment]
That's intended, see [README](https://github.com/peerigon/parse-domain#%EF%B8%8F-effective-tlds--tlds-acknowledged-by-icann).

Use the `icann` property if you don't want private namespaces.
