### ISSUE TITLE
Domain is incorrectly splitting for gov.uk domain

### ISSUE THREAD

**Issue by vinayakwadhwa** [peerigon/parse-domain#135]
both gov and uk are considered as TLDs instead of gov being treated as domain

**Comment by jhnns** [comment]
`.gov.uk` is [listed in the public suffix list](https://publicsuffix.org/list/public_suffix_list.dat) and thus the effective top-level domain (see [this for clarification](https://github.com/peerigon/parse-domain#%EF%B8%8F-effective-tlds--tlds-acknowledged-by-icann)).

You're probably looking for `result.icann`:

```js
const parseResult = parseDomain("something.gov.uk");
const { subDomains, domain, topLevelDomains } = parseResult.icann;

console.log(subDomains); // ["something"]
console.log(domain); // "gov"
console.log(topLevelDomains); // ["uk"]
```
