### ISSUE TITLE
`.com.ru` isn't picked up as a top level domain in the ICANN form

### ISSUE THREAD

**Issue by adrukh** [peerigon/parse-domain#139]
Thanks for a great package!

```js
> parseDomain('www.google.com.ru')
{
  type: 'LISTED',
  hostname: 'www.google.com.ru',
  labels: [ 'www', 'google', 'com', 'ru' ],
  icann: {
    subDomains: [ 'www', 'google' ],
    domain: 'com',
    topLevelDomains: [ 'ru' ]
  },
  subDomains: [ 'www' ],
  domain: 'google',
  topLevelDomains: [ 'com', 'ru' ]
}
```

I'd expect the `icann` object to have `topLevelDomains: [ 'com', 'ru' ]`, as it does for `com.br` for example:
```js
> parseDomain('www.google.com.br')
{
  type: 'LISTED',
  hostname: 'www.google.com.br',
  labels: [ 'www', 'google', 'com', 'br' ],
  icann: {
    subDomains: [ 'www' ],
    domain: 'google',
    topLevelDomains: [ 'com', 'br' ]
  },
  subDomains: [ 'www' ],
  domain: 'google',
  topLevelDomains: [ 'com', 'br' ]
}
```

Happy to open a PR if my expectation is valid, and some initial help is provided (that is, where to start).

**Comment by jhnns** [comment]
I just looked up `com.ru` and `com.br` in the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat).

- `com.br` is below `===BEGIN ICANN DOMAINS===`
- `com.ru` is below `===BEGIN PRIVATE DOMAINS===`

I don't know whether there's a reason for this or if it's just a mistake in the suffix list.

I'm closing this since it would need to be fixed upstream in the suffix list.

**Comment by adrukh** [comment]
Thanks a lot for the speedy reply @jhnns!
I'm sorry I sent you on this debug chase on my behalf. Can I help by adding a troubleshooting section to the readme file that will describe how the public suffix list is used, how to look for issues there, etc.? Or is there such a thing, and I missed it?

**Comment by jhnns** [comment]
Thanks for the offer (and sorry if my previous reply was a little bit harsh 😁).

You could clarify it in this section: https://github.com/peerigon/parse-domain#%EF%B8%8F-effective-tlds--tlds-acknowledged-by-icann
