### ISSUE TITLE
LABEL_INVALID_CHARACTER for a legitimate URL

### ISSUE THREAD

**Issue by peterjoles** [peerigon/parse-domain#141]
The following URL cannot be parsed because it has an underscore in the subdomain.

`const parseResult = parseDomain(fromUrl("https://stackadapt_public.s3.amazonaws.com/icons/adchoices/adchoices.png"));`

https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by jhnns** [comment]
Hi Peter 👋 

we talked about this issue in https://github.com/peerigon/parse-domain/issues/134

There's a debate whether underscores are valid or not 😁. If you want/need to support it, you can relax the validation:

```ts
import { parseDomain, Validation } from "parse-domain";

const parseResult = parseDomain("_jabber._tcp.gmail.com", {
  validation: Validation.Lax,
});
```

See also https://github.com/peerigon/parse-domain#-export-validation

**Comment by peterjoles** [comment]
That's great to know. Thanks for following up. I'll try and relax the validations.
