### ISSUE TITLE
No subdomain detected for withgoogle.com

### ISSUE THREAD

**Issue by Smejicanospal** [peerigon/parse-domain#143]
Parsing the following domain:
```
> await ParseDomain.parseDomain("analytics.withgoogle.com");
{
  type: 'LISTED',
  hostname: 'analytics.withgoogle.com',
  labels: [ 'analytics', 'withgoogle', 'com' ],
  icann: {
    subDomains: [ 'analytics' ],
    domain: 'withgoogle',
    topLevelDomains: [ 'com' ]
  },
  subDomains: [],
  domain: 'analytics',
  topLevelDomains: [ 'withgoogle', 'com' ]
}
```

I would have expected the subdomain array to include "analytics" and for the domain and TLD to be different. 

Here's an example where this works correctly:
```
> await ParseDomain.parseDomain("analytics.google.com");
{
  type: 'LISTED',
  hostname: 'analytics.google.com',
  labels: [ 'analytics', 'google', 'com' ],
  icann: {
    subDomains: [ 'analytics' ],
    domain: 'google',
    topLevelDomains: [ 'com' ]
  },
  subDomains: [ 'analytics' ],
  domain: 'google',
  topLevelDomains: [ 'com' ]
}
```

**Comment by jhnns** [comment]
`withgoogle.com` is listed as [public suffix](https://publicsuffix.org/list/public_suffix_list.dat) and therefore treated as a top-level domain.

It's explained in the README: https://github.com/peerigon/parse-domain#%EF%B8%8F-effective-tlds--tlds-acknowledged-by-icann

**Comment by funnylookinhat** [comment]
@jhnns Aha!  Thank you for explaining that and the link - that makes total sense.  :+1:
