### ISSUE TITLE
Cannot use library in Typescript CJS workspace

### ISSUE THREAD

**Issue by dmattia** [peerigon/parse-domain#148]
The workarounds described in https://github.com/peerigon/parse-domain/issues/142#issuecomment-1172249709 work for me using JavaScript, but do not work when I switch to Typescript.

I created a minimal example here: https://github.com/dmattia/parse-domain-error-example
with a CI Job that just tries to run a typescript file that parses a single domain, with failing output here: https://github.com/dmattia/parse-domain-error-example/actions/runs/3244800468/jobs/5321456053

When I change the `test.ts` file to `test.js`, remove the type annotation, and run with `yarn node test.js`, the output succeeds as expected. It is only with typescript/ts-node where I cannot get this to work at runtime

**Comment by aaaee2** [comment]
We use the NestJS framework and don't have ESM related options at all.
The only way to use the `parse-domain` module in TypeScript is to use a version no older than 5.x.x. It **WAS** a good module, but the author(s) don't seem to care about its fate. I think that it would be possible to make 2 versions - ESM and CJS, but no...

**Comment by jhnns** [comment]
I'm sorry, we switched to ECMAScript modules only. I recommend to also migrate to ESM as this problem will come up everytime a new dependency version switches to ESM.

You should also be able to import ECMAScript modules asynchronously into CommonJS though:

```js
import("parse-domain").then(({parseDomain}) => {
  // This gets executed once the module is loaded
  // You can call parseDomain() now
}):
```

> I think that it would be possible to make 2 versions - ESM and CJS, but no...

Yes, it is possible, but very error prone. A lot of module authors get it wrong to configure it properly and I don't have the time to support two module systems. You're welcome to fork the module and create a CommonJS build.
