### ISSUE TITLE
very slow performance

### ISSUE THREAD

**Issue by sirpy** [peerigon/parse-domain#15]
I've noticed this when i built a webapp that runs on mobiles as a webview (inside chrome).
the method performed really slow and was blocking the UI for a long time when had to parse multiple urls.
it wasnt noticable on desktops but it did on mobile.

after looking at the source code i beleive the issue is the lookup of TLD using regex.
regex are very slow, you have to build the regex on every call to "new Regex".
a match faster approach would be to use object lookup keys.
for example
var tlds = []
tlds['com'] = 1
tlds['co.uk'] = 2
....
then check if tlds[domain] exists.

**Comment by jhnns** [comment]
We're using a trie data structure now which should be a lot faster now. Please re-open if there's still a problem.
