### ISSUE TITLE
How to use require instead of import?

### ISSUE THREAD

**Issue by bwims** [peerigon/parse-domain#151]
Hi,

I'm trying to access this from Node-Red which is based on Node.js

The system allows me to simulate require whereby I can import the entire module as a variable instance.

However, the example wants to import two variables from the module, so I don't know where to go from here.

I tried assigning parseDomain as the variable representing "parse-domain" , but it didn't like that, saying it wasn't a function

I then tried assigning parse-domain to pd and accessing pd.parseDomain  but that gave me "TypeError: Cannot read properties of undefined (reading 'parseDomain')".

As you can see, I am not much of a Javascript programmer!

Any advice would be much appreciated!

B.

**Comment by bwims** [comment]
After further research, it turns out that I can't do what I want because currently Node Red does not support anything but Common JS modules.

Is there any hope that you could somehow provide that as an alternative?

B.

**Comment by jhnns** [comment]
I'm sorry, we switched to ECMAScript modules only with v6.0.0 (https://github.com/peerigon/parse-domain/releases/tag/v6.0.0). You can try a version below v6.0.0 but the list of domains will be outdated.

You should also be able to import ECMAScript modules asynchronously into CommonJS:

```js
import("parse-domain").then(({parseDomain}) => {
  // This gets executed once the module is loaded
  // You can call parseDomain() now
}):
```

**Comment by bwims** [comment]
I know you closed this, but I have to ask:  What do you mean by V6.0.0 ? (I told you I was inexperienced!)

**Comment by bwims** [comment]
I'm going to write this off, since on past performance I won't get a reply until 2024.

Your unexplained solution returned
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.

So bugger it.

**Comment by jhnns** [comment]
@bwims there was a colon instead of a semicolon, but besides that this code snippet works. You can try it out here: https://stackblitz.com/edit/stackblitz-starters-cmcjne?file=index.js (run `node index.js`)

**Comment by jhnns** [comment]
Your error suggests that your code is running inside a [Node VM](https://nodejs.org/dist/latest-v20.x/docs/api/vm.html). There's more going on in your setup which makes it hard to debug.

**Comment by bwims** [comment]
So grateful for your quick reply!   I am using Node Red, which is a low
code development system based on message flow through nodes.  It's based on
Node-JS and it allows you to introduce your own javascript via a function
node and that allows use of imported routines.  Unfortunately, I have no
knowledge of the internals, so I guess if you aren't familiar with NR I am
out of luck!

Thanks

B.
