### ISSUE TITLE
unable to parse domains correctly

### ISSUE THREAD

**Issue by motleycrew** [peerigon/parse-domain#17]
http://jwAA.%6e%65%77%61%69%64%73%65%72%76%69%63%65.ru
http://jwFk.%6e%65%77%61%69%64%73%65%72%76%69%63%65.ru
http://jwCU.%6e%65%77%61%69%64%73%65%72%76%69%63%65.ru
http://jwGe.%6e%65%77%61%69%64%73%65%72%76%69%63%65.ru

parse.domain is unable to parse domains currently. it returns domain has jwGe or jwCU when it should return %6e%65%77%61%69%64%73%65%72%76%69%63%65

**Comment by jhnns** [comment]
We should call `decodeURIComponent`

**Comment by jhnns** [comment]
Will be fixed as soon as we implement https://github.com/peerigon/parse-domain/issues/14#issuecomment-431337570
