### ISSUE TITLE
Cannot find module 'vm' 

### ISSUE THREAD

**Issue by zhixiangw** [peerigon/parse-domain#173]
i use the package in my chrome extension on background.js

When I use version 8.2.2, the console reports an error：Cannot find module 'vm'。 and when I try to switch to version 7.0.0, everything works fine
![pic](https://github.com/user-attachments/assets/e5e1fe37-03f1-4663-8ecc-7bc48929918f)

**Comment by jhnns** [comment]
Not sure what this is about, parse-domain is not using the `vm` module. Please provide a reproducible test case.
