### ISSUE TITLE
Can this be used on the browser?

### ISSUE THREAD

**Issue by claykohut** [peerigon/parse-domain#25]
Hey all -- i'd love to use this library clientside -- is that possible? 

If so, how?

Thanks!

**Comment by jhnns** [comment]
It can be used in modern browsers with ES2015 support. In older browsers, you'll need a compile step via Babel. There's also a PR pending: https://github.com/peerigon/parse-domain/pull/27

Btw: I just decreased the library size down to 30KB minified and gzipped.
