### ISSUE TITLE
parseDomain fails with `Cannot read property '3' of null` when passed an empty string

### ISSUE THREAD

**Issue by hefox** [peerigon/parse-domain#32]
call parseDomain(' '); and it will error with `Cannot read property '3' of null`/ 

normalizedUrl.match(urlParts) does not return an array with 3 elements but the code assumes it will

Adding a check in normalizeUrl likely will fix it
```
function normalizeUrl(url) {
    if (!url || typeof url !== "string" || !url.trim()) {
```

**Comment by jhnns** [comment]
Fixed with `v2.1.8`
