### ISSUE TITLE
⚠️ dev-dependencies were added as dependencies in 2.1.1

### ISSUE THREAD

**Issue by Jolg42** [peerigon/parse-domain#34]
[In 2.1.1 package.json](https://github.com/peerigon/parse-domain/blob/v2.1.1/package.json#L30) 
```
  "dependencies": {
    "chai": "^4.1.2",
    "fs-copy-file-sync": "^1.1.1",
    "got": "^8.0.1",
    "mkdirp": "^0.5.1",
    "mocha": "^4.0.1"
  },
  "devDependencies": {
    "eslint": "^4.12.1",
    "eslint-config-peerigon": "^12.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsdoc": "^3.2.0",
    "nyc": "^11.3.0",
    "standard-version": "^4.2.0"
  }
```

I noticed it because I have a max size limit for dependencies 😉

**Comment by Jolg42** [comment]
@jhnns I guess npm tricked you! ✨

**Comment by Jolg42** [comment]
@jhnns I added a PR (#36) with dependencies moved as dev-dependencies ;-)

**Comment by jhnns** [comment]
See https://github.com/peerigon/parse-domain/pull/36#issuecomment-396337122 :)
