### ISSUE TITLE
Failed to minify the code from this file 

### ISSUE THREAD

**Issue by ats-developer** [peerigon/parse-domain#38]
I have a project which is running fine with local development mode when I try to build for production mode with **npm run build** getting following error, any guidance will be appreciated.

Development Environment : 

- npm --version : 5.6.0
- node -v : v8.11.1

.babelrc as below

```
{
  "presets": ["es2015", "stage-2", "react", "env"],
  "plugins": [
    ["babel-plugin-root-import",
     "babel-plugin-transform-decorators-legacy",
     "transform-object-rest-spread",
     "transform-class-properties"]
  ],
  "env": {
    "debug": true
  }
}

```

> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/parse-domain/lib/parseDomain.js:25 

Read more here: http://bit.ly/2tRViJ9

Let me know if more details are required.

**Comment by abenchi** [comment]
I have the same issue

**Comment by abenchi** [comment]
fixed by using v1.2.0

**Comment by ats-developer** [comment]
Thank you @abenchi  it's working.

**Comment by gokeji** [comment]
Thanks @abenchi , v1.2.0 works with minification. It'll be best of course, if the latest version can continually support this :+1:

**Comment by knoxcard** [comment]
nice job! 💯

Close ticket?

**Comment by jhnns** [comment]
Yay 🎉
