### ISSUE TITLE
Update the list of TLD

### ISSUE THREAD

**Issue by keiko713** [peerigon/parse-domain#41]
Seems like the last update was Dec 2017 (https://github.com/peerigon/parse-domain/commit/df15b19c2df9de00a05104ab7803a6f08f9409cd), but could we update the list to up-to-date one?
Would be nice if there was any "how to update" guide or some update script, which could be used to make PR by anyone. Thanks!

**Comment by taskinosman** [comment]
+1, would you mind to share how you update the publicsuffix library and parse it ?

**Comment by jhnns** [comment]
Starting with [`v2.1.0`](https://github.com/peerigon/parse-domain/releases/tag/v2.1.0), `parse-domain` builds the list on `npm install` which should be sufficient for most people :).

You can also run [`parse-domain/scripts/build-tries.js`](https://github.com/peerigon/parse-domain/blob/master/scripts/build-tries.js) if you need most up-to-date data.

**Comment by jstoeffler** [comment]
It would be nice to have a JS API to hot-reload the list, for apps that don't get deployed frequently
