### ISSUE TITLE
Mocha and Chai as devdeps?

### ISSUE THREAD

**Issue by ryanblock** [peerigon/parse-domain#43]
Stoked about this project, just what we're looking for. However, we're on a strict module size budget, and happened to notice Mocha and Chai are in main deps.

I assume these can be safely moved to dev dependencies – is that the case? If so, happy to PR.

Thanks!

**Comment by ryanblock** [comment]
(Project abandoned?)

**Comment by jhnns** [comment]
This is intended because we're doing a sanity check of the publicsuffix list by running the tests on `npm install`. Mocha and chai won't be included into a bundle because they're not required by the `lib`.
