### ISSUE TITLE
Does not work on Internet explorer

### ISSUE THREAD

**Issue by TrieBr** [peerigon/parse-domain#47]
Internet explorer does not allow const in for loops. As soon as I add

`import parseDomain from 'parse-domain';
`
to the top of my file, my application no longer works in internet explorer (11). I get the following error:

> SCRIPT1053: Const must be initialized

The problem looks like it is on this line: https://github.com/peerigon/parse-domain/blob/bcc24e2aa90000fbdc4bfc5b48f20cba75fafdee/lib/parseDomain.js#L25

In fact, according to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of), Internet Explorer doesn't even support the `for..of` syntax at all.

I can't be the only one having this issue?

**Comment by jhnns** [comment]
Should be fixed with `v2.1.5`.
