### ISSUE TITLE
node scripts/build-tries.js fails on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)

### ISSUE THREAD

**Issue by elasekness** [peerigon/parse-domain#48]
I receive this message trying to install parse-domain.  I have installed the latest versions of node.js and npm.
> parse-domain@2.1.2 postinstall /usr/local/bin/auspice/node_modules/parse-domain
> node scripts/build-tries.js

sh: 1: node: not found
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-tap-event-plugin@3.0.3 requires a peer of react@^16.0.0-0 < 16.4.0 but none was installed.
npm WARN react-tap-event-plugin@3.0.3 requires a peer of react-dom@^16.0.0-0 < 16.4.0 but none was installed.
npm WARN auspice@1.30.2 No repository field.
npm WARN auspice@1.30.2 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-131-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "parse-domain"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! parse-domain@2.1.2 postinstall: `node scripts/build-tries.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the parse-domain@2.1.2 postinstall script 'node scripts/build-tries.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-domain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build-tries.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-domain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-domain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/auspice/npm-debug.log

**Comment by jhnns** [comment]
Looks like `node` is not in your `$PATH`

**Comment by jhnns** [comment]
Fixed with `v3.0.0` 🚀
