### ISSUE TITLE
several parsing issues

### ISSUE THREAD

**Issue by 7c** [peerigon/parse-domain#49]
While working with live squid logs and parsing i came across following issues:

```
ftp://mapasamazonsa.com.ve/ > null  ## maybe problem with ftp ?
http://y399.3466633.be:4/235222/399.html > null ## maybe problem with the port 4 ?
this%20file%20was% > crash with 'TypeError: Cannot read property '3' of null'
```

i wanted give you valid and should-be-working data.

**Comment by taskinosman** [comment]
Adding several more in order to add my 2cents to improve your repo:

```
wss://ie14.zopim.com/s/W/ws/zPYsGUAnWMyJ1XOL/c/1537265376519
wss://mp.sparkchess.com/ 
wss://119.92.223.221.prod.hosts.ooklaserver.net:8080/ws
wss://gscspeedtest1.dctechmicro.com.prod.hosts.ooklaserver.net:8080/ws
ws://lhg2-speedtest.globe.com.ph:8080/ws
wss://s-usc1c-nss-218.firebaseio.com/.ws
```

**Comment by 7c** [comment]
Another one seems to have trouble with a dot at the end of the domain, which is from dns and browser perspective a valid host;

```
http://server.dr.pt./ > null
```

**Comment by 7c** [comment]
Afaik the - is not allowed as last char:
`{ tld: 'zip', domain: '7-1674-', subdomain: '' }`
