### ISSUE TITLE
parsing localhost incorrect

### ISSUE THREAD

**Issue by mediamonks-arjan** [peerigon/parse-domain#5]
http://localhost/signalr
    http://localhost:8080/signalr

both return null

**Comment by mattlubner** [comment]
@mediamonks-arjan I think that's expected behavior?

**Comment by jhnns** [comment]
Well... it's somewhat expected since it's not in the list of known tlds. `localhost` is a special case.

We could solve this with @mattlubner 's PR #3, but it's probably better to just manually add it to the list since it is so common.

**Comment by mattlubner** [comment]
I don't believe `localhost` can be added without changing how that list is built, as all other TLDs expect a preceding dot, whereas `localhost` won't.

It could potentially be hard-coded into `lib/build/buildRegex.js` at line 20 though, like such:
```js
// line 20
src = "module.exports = /localhost|\\.(" + tld + ")$/;";
```

I _believe_ this change, plus the change I added in https://github.com/Vixlet/parse-domain/commit/a9b7912bb2ad7bdb3585ee8ce290b462037dddd4 to `lib/parseDomain.js:72`, would be sufficient for handling `localhost`. Didn't want to add the above change to #3 though, as it felt out-of-scope.

**Comment by mediamonks-arjan** [comment]
Thanks for picking up this issue :)

I was looking for something that could retrieve the domain from any url, and this was the first hit.
Based on the examples in the readme I couldn't make up if localhost would be supported, and when it was not, I added this issue and continued searching for a module that could do that (a more general url-parser). (was quite in a hurry)

Coming back to this, looking at what this module does (splitting a domain in 2-3 parts), parsing localhost doesn't really fit in; the result would have an empty `tld`.
So I don't know if supporting `localhost` fits the purpose of this utility?

Whatever the outcome, I think it would be a good idea to document the usage of localhost in the readme :)

**Comment by jhnns** [comment]
Starting with `v0.2.1` you are allowed to pass in custom tlds: See #3

**Comment by BjoernRave** [comment]
I am not really sure how to use it with localhost:3000 for example. When putting localhost as `privateTld` and going to foo.localhost:3000 it thinks `foo` is the domain and `localhost` the subdomain, how can I make it work on localhost?

**Comment by jhnns** [comment]
The next major version will parse `localhost` as valid, but not listed. `parse-domain` cannot verify the existence of domains that only live in your network.
