### ISSUE TITLE
Spaces in URL

### ISSUE THREAD

**Issue by formatically** [peerigon/parse-domain#55]
Should spaces in the URL cause the parser to return null to indicate a bad URL? Right now, the parser attempts to pull the domain and doesn't return null.

**Comment by jhnns** [comment]
I think if we try to start parsing URLs more seriously, we're opening Pandora's box 😁. We'll leave the parsing stuff to the WHATWG `URL` constructor in the next major release: https://github.com/peerigon/parse-domain/issues/14#issuecomment-431337570
