### ISSUE TITLE
Private suffixes/TLDs?

### ISSUE THREAD

**Issue by stevenvachon** [peerigon/parse-domain#59]
While `com` is public, `pepsi` is private and not mentioned in the public list.

**Comment by jhnns** [comment]
The public suffix list contains private TLDs. Afaik it's used by browsers, so I expect it to be a valid source. Do you have some information about the `pepsi` TLD?

**Comment by stevenvachon** [comment]
I have no information, but http://pepsi redirects to https://pepsi.com

**Comment by jhnns** [comment]
:+1:
