### ISSUE TITLE
Incorrectly pick up cdn.blah.com.s3.amazonaws.com

### ISSUE THREAD

**Issue by hongkongkiwi** [peerigon/parse-domain#6]
Parsing s3 domain urls seems to be incorrect:

For example: cdn.blah.com.s3.amazonaws.com
{ tld: 's3.amazonaws.com',
  domain: 'com',
  subdomain: 'cdn.blah' }

In this case, it should pick up .com from the right hand side (obviously), then amazonaws as the domain, with: cdn.blah.com.s3 as the subdomain

**Comment by hongkongkiwi** [comment]
So from looking through the public suffix list which you choose, we they have a section for ICANN domains and private domains. In my code, I think it's appropriate to switch off processing of 'private' domains. I'll submit a pull request later for this option, it shouldn't significantly affect the code, just provide some extra options for those of us that need it.

**Comment by alsotang** [comment]
+1
just use icann domains

**Comment by alsotang** [comment]
I think we can provide a icann options, such as: 

`parseDomain("foo.blogspot.com", {icann: true}) => {domain: blogspot, subdomain: foo, tld: com}`

**Comment by jhnns** [comment]
Shipped with `1.0.0`
