### ISSUE TITLE
non-breaking space causes parse-domain to fail 

### ISSUE THREAD

**Issue by AurielleP** [peerigon/parse-domain#61]
> ParseDomain('\xa0')
TypeError: Cannot read property '3' of null
    at parseDomain (/node_modules/parse-domain/lib/parseDomain.js:58:22)
>

related to https://github.com/peerigon/parse-domain/issues/32

**Comment by AurielleP** [comment]
newlines also throw this error 

> ParseDomain('\n\nhttp://somewebsite.com/privacy-statement/')
TypeError: Cannot read property '3' of null
    at parseDomain (/node_modules/parse-domain/lib/parseDomain.js:48:22)

**Comment by kulinsj** [comment]
In the case of line breaks in the url, the normalized url is not falsy, so this referenced PR is not sufficient to prevent the error. It would probably be more prudent to sanitize the string in the normalize.js file. I'm now pre-sanitizing the urls i want to parse before handing them to the parse-domain function
`cleanedUrl = url.replace(/(\r\n|\n|\r)/gm, '');`

**Comment by jhnns** [comment]
We delegate all the URL parsing logic to the WHATWG `URL` constructor in a major version update. URL parsing is too complicated. See #14

**Comment by jhnns** [comment]
> In the case of line breaks in the url, the normalizedUrl is not falsy, so this referenced PR is not sufficient to prevent the error

[normalize.js uses `.trim()`](https://github.com/peerigon/parse-domain/blob/601d1929c78093ae0f1323ad42e8dbbbee74ecc0/src/normalize.js#L8) which removes line breaks. A falsy check should be sufficient after that. So I'm going to merge and publish this PR as a fix.

**Comment by jhnns** [comment]
Fixed with `v2.1.8`
