### ISSUE TITLE
unable to install parse-domain via npm install command

### ISSUE THREAD

**Issue by akshaymodi9** [peerigon/parse-domain#72]
using command npm install parse-domain doesnt install the package.
The error is like as follows 

> parse-domain@2.2.0 postinstall /Desktop/workspace/src/node_modules/parse-domain
> run-s build:tries
sh: run-s: command not found

This has happened with the new version 2.2.0.

**Comment by jhnns** [comment]
Fixed with `v2.2.1`. Sorry for any inconvenience, it was a late-night publish 😬

**Comment by Shipow** [comment]
keep it up!

**Comment by dimitrisfasoulas** [comment]
Seems like this resurfaced:
`npm i
> parse-domain@2.3.1 postinstall /Users/dimfas/git/sports-ui/node_modules/parse-domain
> run-s build:tries
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! parse-domain@2.3.1 postinstall: `run-s build:tries`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the parse-domain@2.3.1 postinstall script.`

**Comment by amostech** [comment]
what's the fix for this problem? 2.3.1 also has this issue
