### ISSUE TITLE
TypeScript definition is not available to use on npm module

### ISSUE THREAD

**Issue by mitsuruog** [peerigon/parse-domain#73]
@igorfv 

Related: feat: Add TypeScript typings #66

I tried version `2.3.0` via npm, but the Typings file doesn't appear.
Could you change the build process somethings to copy the Typings file to `lib` folder? 
(I didn't notice build process at that time, sorry)

Thanks.

**Comment by AnandChowdhary** [comment]
Yes, the types are part of the `master` branch, but looks like they're not in the `2.3.0` release:

This should be in this folder; https://unpkg.com/parse-domain@2.3.0/lib/
