### ISSUE TITLE
Can't seem to npm install

### ISSUE THREAD

**Issue by dimitrisfasoulas** [peerigon/parse-domain#77]
Seems like #72  resurfaced ?
`npm i
> parse-domain@2.3.1 postinstall /xxx/node_modules/parse-domain
> run-s build:tries
sh: run-s: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! parse-domain@2.3.1 postinstall: `run-s build:tries`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the parse-domain@2.3.1 postinstall script.`

**Comment by jhnns** [comment]
I can't reproduce this. Can you give me more information? Our CI doesn't capture this error as well.
