### ISSUE TITLE
postinstall on Node.js 12: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by silverwind** [peerigon/parse-domain#78]
```
> node scripts/build-tries.js

Downloading public suffix list from https://publicsuffix.org/list/public_suffix_list.dat... (node:40806) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
ok
```

See [here](https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames) for details on this deprecation.

**Comment by jhnns** [comment]
It's because we're using an outdated version of `got` (https://github.com/peerigon/parse-domain/pull/62) which is because they don't support all the node versions that we do. We need to deprecate that old node version as well which requires a major version bump.

**Comment by silverwind** [comment]
Maybe worth switchting to https://github.com/npm/make-fetch-happen. It comes with proxy support out of the box which is quite valuable to some users.

Thought, I generally would say fetching data updates in post-install scripts should be removed as it makes builds non-deterministic.

**Comment by jhnns** [comment]
Agreed. Related discussion: #42
