### ISSUE TITLE
2nd level domain as custom TLD?

### ISSUE THREAD

**Issue by akost** [peerigon/parse-domain#8]
Is it possible to pass a second level domain as a custom TLD? Looks like it does not work.

e.g. I have foo.example.com and I want to get 'foo' as domain and 'example.com' as TLD.

**Sample code:** 
```
var parseDomain = require('parse-domain');
var url = "foo.example.com";
var parsed_domain = parseDomain(url, { customTlds:[ "example.com"] });

console.log(parsed_domain);
```

**Output**
```
{ tld: 'com', domain: 'example', subdomain: 'foo' }
```

**Expected Output**
```
{ tld: 'example.com', domain: 'foo', subdomain: '' }
```

Thank you!

**Comment by alsotang** [comment]
Do you exactly know whats `tld`???

**Comment by jhnns** [comment]
The `customTlds` option also accepts regular expressions. You should be able to create a pattern for that case :)
