### ISSUE TITLE
Remove `jest` from dependencies

### ISSUE THREAD

**Issue by silverwind** [peerigon/parse-domain#89]
Is a testing framework really needed as a dependency or should it maybe have been in `devDependencies`? Noticed it because of these deprecations:

```
parse-domain > jest > jest-cli > @jest/core > jest-haste-map > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
parse-domain > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()

**Comment by daveisfera** [comment]
Yes, please move `jest` to `devDependencies` so it won't be installed when using `parse-domain`

**Comment by SalvatorePreviti** [comment]
Jest have to be a devDepencency, not a dependency - had to rollback to the old version

**Comment by eridal** [comment]
Any update on this one? What do we need to make this happen?

**Comment by jhnns** [comment]
`jest` is a regular dependency currently because we're running a sanity check after downloading the latest list. We will remove this functionality in future versions. People will have to manually update it.

**Comment by daveisfera** [comment]
This feels like a "heavy" dependency for something so small. Is there a plan to remove this usage in the future?

**Comment by silverwind** [comment]
https://github.com/lupomontero/psl might work as an alternative, zero-dependency module.

**Comment by jhnns** [comment]
Jest is not included into the runtime. It just verifies that the build worked correctly, see https://bundlephobia.com/result?p=parse-domain@2.3.4

But we will remove it in the next major version: https://github.com/peerigon/parse-domain/issues/92#issuecomment-573457759

**Comment by SalvatorePreviti** [comment]
jest has too many dependencies and is not made for this, is made for local development. it references packages that could contain and contain vulnerabilities, makes our docker image huge for no reason, and is also an overkill. We liked this package but if there is not a short term plan to remove jest we are forced to use another solution unfortunately, we are thinking to implement a new package :(

**Comment by esellin** [comment]
+1
As it stands, parse-domain is unfit for production if it brings in jest and all the associated crap.
