### ISSUE TITLE
Some domains are not parsed correctly

### ISSUE THREAD

**Issue by siffash** [peerigon/parse-domain#95]
Input: `domain.spb.ru`
Output: `{domain: "spb", subdomain: "domain", tld: "ru"}`
Expected output: `{domain: "domain", subdomain: "", tld: "spb.ru"}`

Input: `domain.ru.com`
Output: `{domain: "ru", subdomain: "domain", tld: "com"}`
Expected output: `{domain: "domain", subdomain: "", tld: "ru.com"}`

Input: `domain.uk.com`
Output: `{domain: "uk", subdomain: "domain", tld: "com"}`
Expected output: `{domain: "domain", subdomain: "", tld: "uk.com"}`

**Comment by jhnns** [comment]
Are you using [`privateTlds: true`](https://github.com/peerigon/parse-domain#parseoptions)?

**Comment by siffash** [comment]
Tried with this option and it worked, thanks!
